### ISSUE TITLE
Some questions I don't understand

### ISSUE THREAD

**Issue by zhang-mu-zhi** [Alpaca-zip/ultralytics_ros#80]
### Branch

noetic-devel

### Bug

I ran `catkin build` without any problems, but when I ran
`$ roslaunch ultralytics_ros tracker.launch debug:=true`
 there was an error.. This should be a problem with cv_bridge. How did you solve it?

```
[ERROR] [1735107867.980386]: bad callback: <bound method TrackerNode.image_callback of <__main__.TrackerNode object at 0xffff8c9af520>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/nvidia/ultralytics_ws/src/ultralytics_ros/script/tracker_node.py", line 66, in image_callback
    cv_image = self.bridge.imgmsg_to_cv2(msg, desired_encoding="bgr8")
  File "/opt/ros/noetic/lib/python3/dist-packages/cv_bridge/core.py", line 163, in imgmsg_to_cv2
    dtype, n_channels = self.encoding_to_dtype_with_channels(img_msg.encoding)
  File "/opt/ros/noetic/lib/python3/dist-packages/cv_bridge/core.py", line 99, in encoding_to_dtype_with_channels
    return self.cvtype2_to_dtype_with_channels(self.encoding_to_cvtype2(encoding))
  File "/opt/ros/noetic/lib/python3/dist-packages/cv_bridge/core.py", line 91, in encoding_to_cvtype2
    from cv_bridge.boost.cv_bridge_boost import getCvType
ImportError: /lib/aarch64-linux-gnu/libp11-kit.so.0: undefined symbol: ffi_type_pointer, version LIBFFI_BASE_7.0
```

How should I solve it?

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by zhang-mu-zhi** [comment]
The problem has been solved, and you can find the solution by Google.
